#:schema node_modules/wrangler/config-schema.json

name = "portfolio"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "5a28ab4e-0b38-4059-bdd4-66b8af4d6dfb"
