'use client';

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';

import type { ThemePreset } from '../tokens/design-tokens';
import {
  designTokens,
  borderRadiusScale,
  spacingScale,
  typographySizes,
  typographyScaleMultipliers,
  spacingDensityMultipliers,
} from '../tokens/design-tokens';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------
interface ThemeContextValue {
  preset: ThemePreset;
  setPreset: (preset: ThemePreset) => void;
}

const ThemeContext = createContext<ThemeContextValue | null>(null);

export function useTheme(): ThemeContextValue {
  const ctx = useContext(ThemeContext);
  if (!ctx) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return ctx;
}

// ---------------------------------------------------------------------------
// CSS variable generation
// ---------------------------------------------------------------------------
function presetToCSSVariables(preset: ThemePreset): Record<string, string> {
  const vars: Record<string, string> = {};

  // Colors
  vars['--color-primary'] = preset.colors.primary;
  vars['--color-secondary'] = preset.colors.secondary;
  vars['--color-accent'] = preset.colors.accent;
  vars['--color-background'] = preset.colors.background;
  vars['--color-surface'] = preset.colors.surface;
  vars['--color-text'] = preset.colors.text;
  vars['--color-muted'] = preset.colors.muted;

  // Typography families
  vars['--font-heading'] = preset.typography.heading;
  vars['--font-body'] = preset.typography.body;

  // Typography sizes (apply scale multiplier)
  const scaleMultiplier = typographyScaleMultipliers[preset.typography.scale];
  for (const [key, value] of Object.entries(typographySizes)) {
    const baseRem = parseFloat(value);
    vars[`--text-${key}`] = `${(baseRem * scaleMultiplier).toFixed(4)}rem`;
  }

  // Spacing (apply density multiplier)
  const densityMultiplier = spacingDensityMultipliers[preset.spacing];
  for (const [key, value] of Object.entries(spacingScale)) {
    const baseRem = parseFloat(value);
    vars[`--space-${key}`] = `${(baseRem * densityMultiplier).toFixed(4)}rem`;
  }

  // Border radius
  vars['--radius'] = borderRadiusScale[preset.borderRadius];

  // Shadows (static from design tokens)
  for (const [key, value] of Object.entries(designTokens.shadows)) {
    vars[`--shadow-${key}`] = value;
  }

  // Transitions (static from design tokens)
  for (const [key, value] of Object.entries(designTokens.transitions.durations)) {
    vars[`--duration-${key}`] = value;
  }
  for (const [key, value] of Object.entries(designTokens.transitions.easings)) {
    vars[`--easing-${key}`] = value;
  }

  // Breakpoints (static from design tokens)
  for (const [key, value] of Object.entries(designTokens.breakpoints)) {
    vars[`--breakpoint-${key}`] = value;
  }

  return vars;
}

// ---------------------------------------------------------------------------
// Inject CSS variables into <style> tag for Tailwind CSS 4 @theme compatibility
// ---------------------------------------------------------------------------
function generateCSSText(vars: Record<string, string>, presetId: string): string {
  const declarations = Object.entries(vars)
    .map(([prop, val]) => `  ${prop}: ${val};`)
    .join('\n');

  return `/* Theme: ${presetId} — auto-generated by ThemeProvider */\n:root, [data-theme="${presetId}"] {\n${declarations}\n}`;
}

// ---------------------------------------------------------------------------
// ThemeProvider component
// ---------------------------------------------------------------------------
interface ThemeProviderProps {
  preset: ThemePreset;
  children: ReactNode;
}

export function ThemeProvider({ preset: initialPreset, children }: ThemeProviderProps) {
  const [preset, setPreset] = useState<ThemePreset>(initialPreset);

  const cssVars = useMemo(() => presetToCSSVariables(preset), [preset]);
  const cssText = useMemo(() => generateCSSText(cssVars, preset.id), [cssVars, preset.id]);

  // Apply data-theme attribute to document root
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', preset.id);
    return () => {
      document.documentElement.removeAttribute('data-theme');
    };
  }, [preset.id]);

  // Apply CSS variables inline on <html> for immediate availability
  useEffect(() => {
    const root = document.documentElement;
    for (const [prop, val] of Object.entries(cssVars)) {
      root.style.setProperty(prop, val);
    }
    return () => {
      for (const prop of Object.keys(cssVars)) {
        root.style.removeProperty(prop);
      }
    };
  }, [cssVars]);

  const contextValue = useMemo<ThemeContextValue>(
    () => ({ preset, setPreset }),
    [preset],
  );

  return (
    <ThemeContext.Provider value={contextValue}>
      <style dangerouslySetInnerHTML={{ __html: cssText }} />
      {children}
    </ThemeContext.Provider>
  );
}

export default ThemeProvider;
